### ISSUE TITLE
Don't merge callable BED files if multiple CRAMs were given, rather remake them with mosdepth

### ISSUE THREAD

**Issue by nvnieuwk** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#104]
### Description of the bug

It would be better for merged CRAM files to automatically regenerate a new BED file with mosdepth instead of merging the original ones. (This is less channel logic and will have better results)

**Comment by matthdsm** [comment]
I agree.
I would even take this further, run mosdepth by default and drop the `callable_bed` input.

**Comment by nvnieuwk** [comment]
Fixed in #100
