### ISSUE TITLE
Save a process, create index within the module

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#162]
`bcftools concat` supports the `--write-index` flag, so an extra `tabix` process is superfluous.

https://github.com/CenterForMedicalGeneticsGhent/nf-cmgg-germline/blob/bddaca3e32e98535626053afe627bbb64852e36a/subworkflows/local/vcf_concat_bcftools/main.nf#L30-L35

**Comment by nvnieuwk** [comment]
This option creates `.csi` index files, which is not supported by all tools :cry:

**Comment by matthdsm** [comment]
NOOOOOooooooo....;
