### ISSUE TITLE
RFC: run vcf qc per sample instead of per family

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#33]
### Description of question

Would it be better to run variant QC on a per sample base instead of genotyped family vcfs? This would provide more granular results IMO

**Comment by nvnieuwk** [comment]
Yeah true, but I don't think we should drop the overall QC of the final VCF. Maybe some options to specify where the QC has to be done (like `--run_individuals_qc` and `--run_final_qc`?)

**Comment by matthdsm** [comment]
![image](https://user-images.githubusercontent.com/11850640/205853753-603d7058-e9e6-43e5-bc6a-9bc74600263c.png)

**Comment by nvnieuwk** [comment]
Hell yeah let's just add both! Would an option to turn it on or off be helpful?

**Comment by matthdsm** [comment]
let's run both, bcftools is fast anyway and too much params just makes it hard to read

**Comment by nvnieuwk** [comment]
Fair point! I've noticed an occasional error with VCFtools though, so I'm thinking of either removing it or replacing it with something else (don't know what yet)

**Comment by nvnieuwk** [comment]
Added in #35
