### ISSUE TITLE
Save newer files if they already exist in the output directory

### ISSUE THREAD

**Issue by nvnieuwk** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#34]
### Description of the bug

If the output file already exists in the output directory, it doesn't save the newer file. This should be fixed

**Comment by matthdsm** [comment]
https://www.nextflow.io/docs/latest/process.html?highlight=publishdir#publishdir



overwrite | When true any existing file in the specified folder will be overridden (default: true during normal pipeline execution and false when pipeline execution is resumed).
-- | --

**Comment by matthdsm** [comment]
fixed in https://github.com/CenterForMedicalGeneticsGhent/nf-cmgg-germline/pull/31/commits/34c0b8b40811f3a114bcc61fbdc5d5c8ab2fd5ee
