### ISSUE TITLE
Add "validation" subworkflow

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#47]
### Description of feature

Add validation subworkflow which runs RTGtools and/or hap.py to generate a validation report and can be enabled with a flag or something

**Comment by matthdsm** [comment]
nah, that's exactly what I had in mind.
Also add an option for a bed file to limit the regions to investigate

**Comment by matthdsm** [comment]
Might also be worth adding to nf-core, since there's work being done for a "validation" workflow

**Comment by nvnieuwk** [comment]
Perfect! And yes was planning on directly adding it to nf-core :)

**Comment by nvnieuwk** [comment]
Added in #63
