### ISSUE TITLE
Try out bcftools merge instead of CombineGVCFs

### ISSUE THREAD

**Issue by nvnieuwk** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#5]
### Description of feature

Also add a parameter to skip the genotyping and convert the gvcf to vcf using bcftools merge

**Comment by matthdsm** [comment]
https://samtools.github.io/bcftools/bcftools.html#merge

**Comment by matthdsm** [comment]
When combining gvcf into multisample gvcf use:
- `--gvcf`
- `-m none`
