### ISSUE TITLE
Check out `bcftools convert --gvcf2vcf` 

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#6]
### Description of feature

As alternative for GATK GenotypeGVCFs
https://samtools.github.io/bcftools/bcftools.html#convert

**Comment by nvnieuwk** [comment]
Fixed with #8

**Comment by nvnieuwk** [comment]
After some more testing, I noticed `bcftools convert` doesn't do much to change the GVCF to VCF and still emits a huge file containing non-ref sites. Even after filtering with `bcftools view` some sites are still present and the the sites containing actual variants still got the additional `<NON-REF>` as ALT nucleotide. 

I'll look for a new tool (e.g. (gvcftools)[https://sites.google.com/site/gvcftools/]) that can perform this conversion in an easier way.

**Comment by nvnieuwk** [comment]
the `extract_variants` tool from `gvcftools` isn't able to parse multisample gvcf files (https://github.com/sequencing/gvcftools/issues/9) and it doesn't seem that it will be fixed soon...

**Comment by nvnieuwk** [comment]
`bcftools merge` does not seem to work with `GenotypeGVCFs` every time

**Comment by nvnieuwk** [comment]
# Comparison of GenotypeGVCFs with bcftools view/convert
=> The GVCFs were merged using CombineGVCFs

| | CPU hours | tool(s) runtime | tool(s) memory | tool(s) cpus |
|-|-----------|--------------|-------------|-----------|
| GenotypeGVCFs | 12.0 | 0.6m | 1.4GB | 1.5
| bcftools view & convert | 11.5 | 0.0m + 0.2m = 0.2m | 20MB + 8MB = 28MB | 1.8 + 1.0 = 2.8 |
