### ISSUE TITLE
Improve scattering even more 

### ISSUE THREAD

**Issue by nvnieuwk** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#60]
### Description of feature

Improve scattering so that the coverage is also taken into account before the variant calling.

**Comment by nvnieuwk** [comment]
Could make use of the coverage data retrieved from mosdepth (extra field that contains `NO_COVERAGE`, `LOW_COVERAGE` or `CALLABLE` => default to `CALLABLE` if nothing is in the fourth column) 

`LOW_COVERAGE` regions could only count for half or 1/3 of the size it would normally add.

**Comment by nvnieuwk** [comment]
WES BED files could also be run through Mosdepth to check coverage for these regions if it's not in there yet

**Comment by nvnieuwk** [comment]
It could also be a good idea to convert the groovy code to a bash script. The current Groovy scatter job takes about an hour for a BED file created with mosdepth

**Comment by nvnieuwk** [comment]
The solution to end it all: https://github.com/brentp/goleft/tree/master/indexsplit#indexsplit

**Comment by matthdsm** [comment]
Using  `indexsplit` would enable us to ditch `mosdepth` for callable regions.
This tool outputs a 4 column bed with regions to parallelise. This means we'd no longer pass a bed file to gatk but a regions string.

so we're going to do
regions.bed -> intersect with ROI -> read bed line by line -> if row[3] > 0 -> channel item per region

**Comment by nvnieuwk** [comment]
Scattering is now the most optimal it can be for WGS
