### ISSUE TITLE
Don't overwrite multiqc in the outdir 

### ISSUE THREAD

**Issue by nvnieuwk** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#66]
### Description of the bug

When running the pipeline multiple times, the multiqc folder also gets overwritten basically deleting all statistics of the files from the previously created VCFs

**Comment by matthdsm** [comment]
Possible fix is to "import" all found reports into a channel and use as input for MQC

**Comment by nvnieuwk** [comment]
Hmmm you got something good there! This would be even better than having multiple different reports. I'll give it a go when I work on those

**Comment by nvnieuwk** [comment]
This shouldn't be a problem on the in house cluster
