### ISSUE TITLE
Haplotypecaller is overprovisioned

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#67]
### Description of the bug

Haplotypecaller is set to `process_medium` after which the setting are overrided in `modules.conf` to increase time and set cpu's to 1

This causes the job to request too much memory.
I suggest setting to `process_single` which _should_ be enough for single chunks (pending execution report)

**Comment by matthdsm** [comment]
Execution report shows mem usage of max 4.GB, so definitely overprovisioned!

**Comment by nvnieuwk** [comment]
Thank you this was on my todo list :)
