### ISSUE TITLE
Standardize resource request to 8c/64gb

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#68]
### Description of feature

We are standardizing our cluster to 8c/64gb so `base.conf` should reflect that

**Comment by matthdsm** [comment]
nope, default configs should be geared towards our own cluster so the pipeline runs with as minimal config as possible.
Extra settings for HPC or other clusters are less important

**Comment by nvnieuwk** [comment]
Fair point!
