### ISSUE TITLE
validation: Investigate bedtools jaccard

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#71]
### Description of feature

https://bedtools.readthedocs.io/en/latest/content/tools/jaccard.html

Interval similarity score

**Comment by nvnieuwk** [comment]
Do you want these as QC or something? I don't really see what this could improve? (But then again I can be blind 😁)

**Comment by matthdsm** [comment]
Can be used within the validation workflow to check give a similarity score of truth vcf vs called vcf
idea stolen from [slack](https://nfcore.slack.com/archives/CGFUX04HZ/p1677830396319879)

**Comment by nvnieuwk** [comment]
Oh I didn't even think of that, thank you!

**Comment by nvnieuwk** [comment]
Added in #107
