### ISSUE TITLE
Re-add ROI support for WES

### ISSUE THREAD

**Issue by nvnieuwk** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#75]
### Description of feature

ROI support has for now been disabled due to the addition of `goleft_indexsplit`. This should be solved in a new creative way

**Comment by nvnieuwk** [comment]
https://bedtools.readthedocs.io/en/latest/content/tools/coverage.html
Compute coverage per region with the `-d` flag. Write a script that divides the BED into multiple other BED files of even coverage

**Comment by matthdsm** [comment]
bedtools coverage == mosdepth but much slower

**Comment by nvnieuwk** [comment]
That's what I thought too, but mosdepth doesn't retain the original regions of the ROI file which was a big nope for me

**Comment by nvnieuwk** [comment]
Added in #92
