### ISSUE TITLE
Possible improvement to vep

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#76]
### Description of feature

xref https://github.com/nf-core/modules/pull/3006#issuecomment-1462109031

Perhaps we _could_ merge all vcf's into a multisample per run, then run `vep` and split again. That way, we only need to run vep once, or once per chunk.

**Comment by nvnieuwk** [comment]
How will that be more efficient? Wouldn't that be aprox. the same as running VEP once per family VCF?

**Comment by matthdsm** [comment]
run vep 1 * #chunks  > running vep  X * #chuncks ?

The reasoning behind this is that each variant get's annotated, regardless of sample. This eliminates the overhead of shared variants (the majority in most cases)

**Comment by nvnieuwk** [comment]
Ooooh that's smart!!! That's a very good point! Will this be in the nf-core subworkflow soon?

**Comment by matthdsm** [comment]
hahaahhahahahahahahaha

nope..

**Comment by nvnieuwk** [comment]
Meh I thought that would be an easy addition 😁. Let's just set this on a not so high priority for now
