### ISSUE TITLE
Add file check for SDF folder

### ISSUE THREAD

**Issue by nvnieuwk** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#84]
### Description of the bug

Currently the SDF folder isn't checked to see if it exists, this should be added (it's only detected by the first process that needs it)

**Comment by matthdsm** [comment]
Also set validate to `false` by default

**Comment by nvnieuwk** [comment]
For now the logic works like this: If samples have been given a `truth_vcf`, validation will run on only those samples unless `--validate false` has been given. I set it to `true` because of this safe guard :)

**Comment by matthdsm** [comment]
The workflow tries to stage a non-existent sdf tar file if validate is set to true, causing it to fail

**Comment by nvnieuwk** [comment]
Hmm good point, I'll see if I can find a workaround for that. If not I'll set it to `false` by default

**Comment by nvnieuwk** [comment]
Also we should probably add the SDF tar folder to the HPC :)

**Comment by nvnieuwk** [comment]
Fixed in v1.1.1
