### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-germline#98]
### Description of feature

Add a dockerfile containing all the requirements for the pipeline, so we can run it as a single "tool" on nomad/galaxy/whatever

**Comment by nvnieuwk** [comment]
Do you mean a container that contains all tools needed or just a container able to start the pipeline and download the relevant containers itself?

**Comment by matthdsm** [comment]
A container with all the tools installed so the pipeline can run inside the container without creating conda envs or running docker

**Comment by nvnieuwk** [comment]
That's gonna be a challenge, but I'll give it a go :)

**Comment by nvnieuwk** [comment]
I've managed to create a container without `somalier` and `groovy` (needed when adding ped headers, but that can be rewritten). Is it bad that `somalier` isn't part of it?
